# MAINTAINER Blockchain_team
version: "3"
services:
  bootnode:
    build: .
    container_name: ethereumwithapi
    user: "root"
    ports:
      - "30302:30302"
      - "10010:10010"
    volumes:
      - ./common:/opt/common
      - ./node:/opt/node
    command: sh ./opt/common/startBootnode.sh
